[package]
authors = ["FloezeTv <floeze@floeze.tv>"]
categories = []
description = "Repository for NAViz"
edition = "2021"
keywords = ["naviz", "repository"]
license = "AGPL-3.0-or-later"
name = "naviz-repository"
repository = "https://github.com/FloezeTv/NAViz"
version = "0.0.0"

[dependencies]
