[package]
authors = ["FloezeTv <floeze@floeze.tv>"]
categories = []
description = "State for NAViz"
edition = "2021"
keywords = ["naviz", "state"]
license = "AGPL-3.0-or-later"
name = "naviz-state"
repository = "https://github.com/FloezeTv/NAViz"
version = "0.2.0"

[dependencies]
