[package]
authors = ["FloezeTv <floeze@floeze.tv>"]
categories = ["visualization", "rendering"]
description = "Renderer for NAViz"
edition = "2021"
keywords = ["naviz", "renderer"]
license = "LGPL-3.0-or-later"
name = "naviz-renderer"
repository = "https://github.com/FloezeTv/NAViz"
version = "0.0.0"

[dependencies]
bytemuck = "1.18.0"
glam = {version = "0.29.0", features = ["bytemuck"]}
naga_oil = "0.14.0"
wgpu = {version = "0.20.0", default-features = false, features = ["wgsl", "naga-ir"]}
