name: Check Commit Messages

# This workflow checks that commit messages on pull requests follow conventional commits.

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.ts
