name: Build Releases

# <>

on:
  push:
    tags:
      - "v*" # Build whenever a full version of naviz is released

env:
  CACHE_KEY: naviz-desktop

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            image: macos-latest
          - target: x86_64-apple-darwin
            image: macos-13
          - target: aarch64-unknown-linux-gnu
            image: ubuntu-24.04-arm
          - target: i686-unknown-linux-gnu
            image: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-latest
          - target: aarch64-pc-windows-msvc
            image: windows-11-arm
          - target: i686-pc-windows-msvc
            image: windows-latest
          - target: x86_64-pc-windows-msvc
            image: windows-latest
    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch full history with tags
          fetch-depth: 0
          # but only history (treeless)
          filter: "tree:0"
      - name: Restore cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.CACHE_KEY }}
      - name: Install Rust toolchain
        run: rustup toolchain install ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./target/naviz-gui
          name: naviz-${{ matrix.target }}

