name: Build Releases

# <>

on:
  push:
    tags:
      - "v*" # Build whenever a full version of naviz is released

env:
  CACHE_KEY: naviz-desktop

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            image: macos-latest
          - target: x86_64-apple-darwin
            image: macos-latest
          - target: aarch64-unknown-linux-gnu
            image: ubuntu-latest
            additional-packages: gcc-aarch64-linux-gnu
            environment: CC=aarch64-linux-gnu-gcc
          - target: i686-unknown-linux-gnu
            image: ubuntu-latest
            additional-packages: gcc-i686-linux-gnu
            environment: CC=i686-linux-gnu-gcc
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-latest
          - target: aarch64-pc-windows-msvc
            image: windows-latest
          - target: i686-pc-windows-msvc
            image: windows-latest
          - target: x86_64-pc-windows-msvc
            image: windows-latest
      fail-fast: false
    runs-on: ${{ matrix.image }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Install additional packages
        run: sudo apt install -y ${{ matrix.additional-packages }}
        if: ${{ matrix.additional-packages != '' }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch full history with tags
          fetch-depth: 0
          # but only history (treeless)
          filter: "tree:0"
      - name: Restore cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.CACHE_KEY }}-${{ matrix.target}}
      - name: Install Rust toolchain
        run: rustup toolchain install stable --target ${{ matrix.target }}
      - name: Build
        working-directory: gui
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./target/release/naviz-gui
          name: naviz-${{ matrix.target }}

