name: Format

# This workflow checks the formatting of the code and fails if it is not formatted.

on:
  push:

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check Rust Formatting
        run: cargo fmt --check

