name: GitHub Pages nightly web builds

# This workflow builds the latest web-version of naviz an publishes it to GitHub Pages.

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

# Cancel any old builds when starting a new build
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  CACHE_KEY: gh-pages_naviz-web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch full history with tags
          fetch-depth: 0
          # but only history (treeless)
          filter: "tree:0"
      - name: Restore cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.CACHE_KEY }}
      - name: Install Rust toolchain
        run: rustup target add wasm32-unknown-unknown
      - name: Setup cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install trunk
        # `--force`: https://github.com/Swatinem/rust-cache/issues/204
        run: cargo binstall trunk --force
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build
        working-directory: gui
        run: trunk build --release --public-url "${{ steps.pages.outputs.base_path }}"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./gui/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
