name: Lint

on:
  push:

env:
  CACHE_KEY: lint-rust

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # fetch full history with tags
          fetch-depth: 0
          # but only history (treeless)
          filter: "tree:0"
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.CACHE_KEY }}
          cache-on-failure: true
      - name: Install tools
        run: cargo install clippy-sarif
      - name: Run Clippy
        run: cargo clippy --all-features --message-format=json | clippy-sarif > clippy.sarif
      - name: Upload Findings
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: clippy.sarif

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check Rust Formatting
        run: cargo fmt --check

