name: Lint

on:
  pull_request:
  push:

env:
  CACHE_KEY: lint-rust
  # Fail on all warnings (including lints)
  # RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch full history with tags
          fetch-depth: 0
          # but only history (treeless)
          filter: "tree:0"
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.CACHE_KEY }}
          cache-on-failure: true
      - run: cargo install clippy-sarif
      - uses: reviewdog/action-setup@v1
      - name: Run Clippy
        run: cargo clippy --all-features --message-format=json | clippy-sarif > clippy.sarif
      - name: Annotate PR
        run: cat clippy.sarif | reviewdog -name="clippy" -f=sarif -reporter=github-pr-check -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload findings
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: clippy.sarif

