name: Lint Rust

on:
  pull_request:
  push:

env:
  CACHE_KEY: lint-rust
  # Fail on all warnings (including lints)
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.CACHE_KEY }}
      - uses: clechasseur/rs-clippy-check@v4
        with:
          args: --all-targets --all-features

