name: Lint Rust

on:
  pull_request:
  push:

env:
  CACHE_KEY: lint-rust
  # Fail on all warnings (including lints)
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.CACHE_KEY }}
      - name: Clippy
        id: clippy
        run: cargo clippy --all-targets --all-features
      - name: Generate Clippy Report
        if: ${{ steps.clippy.conclusion == 'failure' }}
        run: |
          echo "# Clippy" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          cargo clippy -q >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY

