name: Lint

# This workflow lints the code and uploads new findings to GitHub.
# Newly introduced findings will be added to pull requests as review comments.

on:
  push:

env:
  CACHE_KEY: lint-rust

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache-key: ${{ env.CACHE_KEY }}
      # - name: Setup Rust Toolchain
      #   uses: dtolnay/rust-toolchain@stable
      #   with:
      #     components: clippy
      # - name: Restore Rust Cache
      #   uses: Swatinem/rust-cache@v2
      #   with:
      #     key: ${{ env.CACHE_KEY }}
      #     cache-on-failure: true
      - name: Install tools
        run: cargo install clippy-sarif sarif-fmt
      - name: Run Clippy
        run: cargo clippy --all-features --all-targets --message-format=json | sort -u | clippy-sarif | tee clippy.sarif | sarif-fmt
      - name: Upload Findings
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: clippy.sarif
