name: Publish Crates

# This workflow publishes all crates in this repository

on:
  push:
    tags:
      - "v*" # Publish whenever a full version of naviz is released

env:
  CACHE_KEY: publish

jobs:
  publish:
    name: Publish Crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ env.CACHE_KEY }}
      - name: Install Tools
        run: cargo install cargo-workspaces
      - name: Publish Crates
        env:
          TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo ws publish --token "$TOKEN" --publish-as-is --skip-published
